package debt

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/samestrin/atcr/internal/log"
)

// RenderDashboard renders a deterministic Markdown dashboard from recs: totals,
// a per-severity breakdown, a per-component rollup, an age profile grouped by
// calendar month (so the render never drifts merely because time passed), and a
// top-priority list of the topN highest unresolved items.
//
// The output contains NO generation timestamp: a stable render is what lets
// `atcr debt dashboard --check` detect real content drift rather than clock
// movement. Free-text problem statements in the top list are passed through the
// secret-token redactor so a key accidentally pasted into a finding never lands
// in a published dashboard.
func RenderDashboard(recs []Record, topN int) string {
	red := log.NewRedactor("") // empty root: token scrub only, no path relativization

	// Severity/component/top are all independent of the wall clock. Summarize
	// needs a `now` only for its relative-age buckets, which the dashboard does
	// not use (it renders a time-invariant by-month view below), so a zero time
	// is passed and ByAge is ignored.
	sum := Summarize(recs, time.Time{}, topN)

	var b strings.Builder
	b.WriteString("# Technical Debt Dashboard\n\n")
	b.WriteString("_Generated by `atcr debt dashboard` — do not edit by hand; regenerate to update._\n\n")

	fmt.Fprintf(&b, "**Total:** %d  |  **Open:** %d  |  **Deferred:** %d  |  **Resolved:** %d\n\n",
		sum.Total, sum.Open, sum.Deferred, sum.Resolved)

	// By severity.
	b.WriteString("## By Severity\n\n")
	b.WriteString("| Severity | Open | Deferred | Resolved | Total |\n")
	b.WriteString("|----------|------|----------|----------|-------|\n")
	for _, c := range sum.BySeverity {
		fmt.Fprintf(&b, "| %s | %d | %d | %d | %d |\n", c.Severity, c.Open, c.Deferred, c.Resolved, c.Total)
	}
	b.WriteString("\n")

	// By component.
	b.WriteString("## By Component\n\n")
	if len(sum.ByComponent) == 0 {
		b.WriteString("_No items._\n\n")
	} else {
		b.WriteString("| Component | Items |\n|-----------|-------|\n")
		for _, c := range sum.ByComponent {
			fmt.Fprintf(&b, "| %s | %d |\n", sanitizeCell(c.Component), c.Total)
		}
		b.WriteString("\n")
	}

	// By age — unresolved items grouped by shard month (YYYY-MM), oldest first.
	b.WriteString("## By Age (unresolved, by month)\n\n")
	months := monthHistogram(recs)
	if len(months) == 0 {
		b.WriteString("_No unresolved items._\n\n")
	} else {
		b.WriteString("| Month | Unresolved |\n|-------|------------|\n")
		for _, m := range months {
			fmt.Fprintf(&b, "| %s | %d |\n", m.month, m.count)
		}
		b.WriteString("\n")
	}

	// Top priority — most-severe, then oldest, unresolved items.
	b.WriteString("## Top Priority\n\n")
	if len(sum.Top) == 0 {
		b.WriteString("_No unresolved items._\n")
	} else {
		b.WriteString("| Severity | File | Est | Problem |\n|----------|------|-----|---------|\n")
		for _, r := range sum.Top {
			fmt.Fprintf(&b, "| %s | %s | %d | %s |\n",
				r.Severity, sanitizeCell(r.File), r.EstMinutes, sanitizeCell(red.Redact(r.Problem)))
		}
	}

	return b.String()
}

type monthCount struct {
	month string
	count int
}

// monthHistogram counts unresolved items per shard month (the YYYY-MM prefix of
// the shard date), sorted oldest month first. A date too short to carry a month
// prefix is bucketed under "unknown", sorted last.
func monthHistogram(recs []Record) []monthCount {
	counts := map[string]int{}
	for _, r := range recs {
		if !unresolved(r) {
			continue
		}
		m := "unknown"
		if len(r.Date) >= 7 {
			m = r.Date[:7]
		}
		counts[m]++
	}
	out := make([]monthCount, 0, len(counts))
	for m, n := range counts {
		out = append(out, monthCount{month: m, count: n})
	}
	sort.Slice(out, func(i, j int) bool {
		// "unknown" sorts last; otherwise oldest month first.
		if (out[i].month == "unknown") != (out[j].month == "unknown") {
			return out[j].month == "unknown"
		}
		return out[i].month < out[j].month
	})
	return out
}
