// Package quickstart holds the data layer for `atcr quickstart`: the bundled
// synthetic-provider manifest, the registry.yaml generator that turns it into a
// working provider + agent roster, and the pure transform used by the scheduled
// manifest-refresh job. All logic here is I/O-free so it stays unit-testable;
// file writes and interactive prompts live in cmd/atcr/quickstart.go.
package quickstart

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"net/url"
	"strings"
	"unicode"
)

// syntheticManifest is the bundled default provider/model set. It is regenerated
// by the scheduled refresh job (cmd/refresh-manifest); keep the shape in sync
// with Manifest.
//
//go:embed synthetic.json
var syntheticManifest []byte

// Provider describes the synthetic OpenAI-compatible endpoint. Only the env var
// NAME is carried — the key value is never part of the manifest or any file
// atcr writes (matching atcr's env-resolved-at-invoke-time posture).
type Provider struct {
	Name      string `json:"name"`
	BaseURL   string `json:"base_url"`
	APIKeyEnv string `json:"api_key_env"`
}

// Manifest is the bundled synthetic-provider defaults shipped with atcr and
// regenerated by the scheduled refresh job. SignupURL + Referral drive the
// onboarding link; Provider + Models seed the generated registry.yaml.
type Manifest struct {
	SignupURL string   `json:"signup_url"`
	Referral  string   `json:"referral"`
	Provider  Provider `json:"provider"`
	Models    []string `json:"models"`
}

// LoadManifest parses and validates the embedded synthetic manifest. Validation
// is defense-in-depth against a malformed refresh: the provider name, base_url,
// api_key_env, and at least one model are required.
func LoadManifest() (*Manifest, error) {
	var m Manifest
	if err := json.Unmarshal(syntheticManifest, &m); err != nil {
		return nil, fmt.Errorf("parsing synthetic manifest: %w", err)
	}
	if err := m.validate(); err != nil {
		return nil, err
	}
	return &m, nil
}

// validate rejects a structurally-incomplete manifest so a bad refresh can never
// generate a broken registry.yaml.
func (m *Manifest) validate() error {
	switch {
	case strings.TrimSpace(m.SignupURL) == "":
		return fmt.Errorf("synthetic manifest: signup_url is required")
	case strings.TrimSpace(m.Provider.Name) == "":
		return fmt.Errorf("synthetic manifest: provider.name is required")
	case strings.TrimSpace(m.Provider.BaseURL) == "":
		return fmt.Errorf("synthetic manifest: provider.base_url is required")
	case strings.TrimSpace(m.Provider.APIKeyEnv) == "":
		return fmt.Errorf("synthetic manifest: provider.api_key_env is required")
	case len(m.Models) == 0:
		return fmt.Errorf("synthetic manifest: at least one model is required")
	}
	if _, err := url.Parse(m.SignupURL); err != nil {
		return fmt.Errorf("synthetic manifest: signup_url is invalid: %w", err)
	}
	// Provider.Name, BaseURL, and APIKeyEnv are emitted verbatim into
	// registry.yaml (RegistryYAML lines ~121-123). A control character — a newline
	// especially — could forge new YAML keys/agents, a strictly worse injection
	// than the model-id case guarded below. Apply the same scan symmetrically.
	for _, f := range []struct{ name, value string }{
		{"provider.name", m.Provider.Name},
		{"provider.base_url", m.Provider.BaseURL},
		{"provider.api_key_env", m.Provider.APIKeyEnv},
	} {
		if strings.IndexFunc(f.value, func(r rune) bool { return unicode.IsControl(r) }) >= 0 {
			return fmt.Errorf("synthetic manifest: %s contains a control character", f.name)
		}
		if !isSafeYAMLScalar(f.value) {
			return fmt.Errorf("synthetic manifest: %s is not a safe plain YAML scalar", f.name)
		}
	}
	for i, model := range m.Models {
		if strings.TrimSpace(model) == "" {
			return fmt.Errorf("synthetic manifest: models[%d] is empty", i)
		}
		// Model ids are emitted verbatim as `model: <id>` lines in the generated
		// registry.yaml. A control character (esp. a newline) in an id sourced from
		// the live /models endpoint could forge YAML structure, so reject them at
		// the load boundary — defense-in-depth against a hostile refresh response.
		if strings.IndexFunc(model, func(r rune) bool { return unicode.IsControl(r) }) >= 0 {
			return fmt.Errorf("synthetic manifest: models[%d] contains a control character", i)
		}
		if !isSafeYAMLScalar(model) {
			return fmt.Errorf("synthetic manifest: models[%d] is not a safe plain YAML scalar", i)
		}
	}
	return nil
}

// isSafeYAMLScalar reports whether s can be emitted as a bare `key: <s>` value in
// registry.yaml without being reinterpreted by the YAML parser. RegistryYAML
// writes provider fields and model ids by string concatenation, not through a
// YAML encoder, so a value like `gpt: evil` (breaks parsing — a DoS), `gpt # x`
// (silently truncated at the comment), or `[a,b]` (becomes a list, not a string)
// must be rejected at the load boundary. A colon NOT followed by a space is fine
// — real ids (hf:org/model) and the https:// base_url rely on it.
func isSafeYAMLScalar(s string) bool {
	if s == "" || s != strings.TrimSpace(s) {
		return false
	}
	// Characters that cannot begin a plain scalar (they open a flow collection,
	// anchor, alias, tag, block scalar, quote, directive, comment, etc.).
	if strings.ContainsRune("!&*[]{}#|>@`\"'%,", rune(s[0])) {
		return false
	}
	// '-', '?', ':' are indicators only when the first char is followed by a space
	// (or is the whole value).
	if (s[0] == '-' || s[0] == '?' || s[0] == ':') && (len(s) == 1 || s[1] == ' ') {
		return false
	}
	// Inside the scalar: ": " opens a mapping, a trailing ":" opens a mapping, and
	// " #" starts a comment — each breaks `key: <value>` emission.
	if strings.Contains(s, ": ") || strings.HasSuffix(s, ":") || strings.Contains(s, " #") {
		return false
	}
	return true
}

// SignupLink returns the signup URL with the referral code appended as a query
// param when set. A blank referral yields the bare URL — atcr ships without
// claiming anyone's referral credit; set "referral" in synthetic.json to enable
// tracking.
func (m *Manifest) SignupLink() string {
	if strings.TrimSpace(m.Referral) == "" {
		return m.SignupURL
	}
	u, err := url.Parse(m.SignupURL)
	if err != nil {
		return m.SignupURL
	}
	q := u.Query()
	q.Set("referral", m.Referral)
	u.RawQuery = q.Encode()
	return u.String()
}

// RegistryYAML renders the ~/.config/atcr/registry.yaml content: the synthetic
// provider plus one agent per roster persona, bound round-robin across the
// manifest's models. Each agent's name equals its persona so the roster written
// to .atcr/config.yaml (persona names) resolves against these agents. The output
// only uses keys the strict registry loader knows, so it parses cleanly.
func RegistryYAML(m *Manifest, roster []string) string {
	var b strings.Builder
	b.WriteString("# atcr user registry — see docs/registry.md\n")
	b.WriteString("# Written by `atcr quickstart`. Providers + agents live here; the roster\n")
	b.WriteString("# (agent names) lives in .atcr/config.yaml. The API key value is NEVER stored\n")
	b.WriteString("# here — only the env var NAME. Set it in your environment:\n")
	fmt.Fprintf(&b, "#   export %s=...\n", m.Provider.APIKeyEnv)
	b.WriteString("providers:\n")
	fmt.Fprintf(&b, "  %s:\n", m.Provider.Name)
	fmt.Fprintf(&b, "    base_url: %s\n", m.Provider.BaseURL)
	fmt.Fprintf(&b, "    api_key_env: %s\n", m.Provider.APIKeyEnv)
	// Defensive: LoadManifest guarantees >=1 model, but RegistryYAML is exported
	// and a direct caller could pass an empty set — the round-robin modulo would
	// panic on len 0. Emit the provider block only rather than crash.
	if len(m.Models) == 0 {
		return b.String()
	}
	if len(roster) == 0 {
		return b.String()
	}
	b.WriteString("agents:\n")
	for i, persona := range roster {
		model := m.Models[i%len(m.Models)]
		fmt.Fprintf(&b, "  %s:\n", persona)
		fmt.Fprintf(&b, "    persona: %s\n", persona)
		fmt.Fprintf(&b, "    provider: %s\n", m.Provider.Name)
		fmt.Fprintf(&b, "    model: %s\n", model)
	}
	return b.String()
}
