// Package quickstart holds the data layer for `atcr quickstart`: the bundled
// synthetic-provider manifest, the registry.yaml generator that turns it into a
// working provider + agent roster, and the pure transform used by the scheduled
// manifest-refresh job. All logic here is I/O-free so it stays unit-testable;
// file writes and interactive prompts live in cmd/atcr/quickstart.go.
package quickstart

// Provider describes the synthetic OpenAI-compatible endpoint. Only the env var
// NAME is carried — the key value is never part of the manifest or any file
// atcr writes (matching atcr's env-resolved-at-invoke-time posture).
type Provider struct {
	Name      string `json:"name"`
	BaseURL   string `json:"base_url"`
	APIKeyEnv string `json:"api_key_env"`
}

// Manifest is the bundled synthetic-provider defaults shipped with atcr and
// regenerated by the scheduled refresh job. SignupURL + Referral drive the
// onboarding link; Provider + Models seed the generated registry.yaml.
type Manifest struct {
	SignupURL string   `json:"signup_url"`
	Referral  string   `json:"referral"`
	Provider  Provider `json:"provider"`
	Models    []string `json:"models"`
}

// LoadManifest parses and validates the embedded synthetic manifest. Stub —
// implemented in GREEN.
func LoadManifest() (*Manifest, error) { return nil, nil }

// SignupLink returns the signup URL with the referral code appended when set.
// Stub — implemented in GREEN.
func (m *Manifest) SignupLink() string { return "" }

// RegistryYAML renders the ~/.config/atcr/registry.yaml content: the synthetic
// provider plus one agent per roster persona, bound round-robin across the
// manifest's models. Stub — implemented in GREEN.
func RegistryYAML(m *Manifest, roster []string) string { return "" }
